apiVersion: apps/v1
kind: Deployment
metadata:
  name: luna-frontend
  namespace: luna
  labels:
    owner: ui_team
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80